### ISSUE TITLE
.parse is not available on TsjsonParser

### ISSUE THREAD

**Issue by moltar** [ostrowr/ts-json-validator#10] opened 2019-11-03 16:59 UTC
This:

```
  public parse = (text: string, skipValidation = false): Validated<T> => {
    const data: unknown = JSON.parse(text);
```

Gets compiled to:

```
class TsjsonParser {
    constructor(schema) {
        this.parse = (text, skipValidation = false) => {
            const data = JSON.parse(text);
            if (skipValidation) {
                return data;
            }
            this.validate(data);
            return data;
        };
        this.schema = schema;
        const ajv = new ajv_1.default();
        this.validator = ajv.compile(schema);
    }
```

And IDE cannot infer this as an available class method.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/491247/68088886-61d96300-fe31-11e9-89e8-8678a2d77514.png">

**Comment by ostrowr** [comment] 2019-11-03 17:39
That's odd. Which version of TypeScript are you using in your IDE? Intellisense should infer

- `schema`
- `validate`
- `parse`

There's no `data` anywhere.

I've made a bunch of changes in the last 2 days, can you try latest master and see if you're still running into this issue?

The generated code looks right, but can you check if the generated types match as well? tsjson-parser.d.ts should have something like

```
export declare class TsjsonParser<T extends SchemaLike> {
    readonly schema: T;
    private readonly validator;
    constructor(schema: T);
    validate(data: unknown): asserts data is Validated<T>;
    parse: (text: string, skipValidation?: boolean) => T[typeof InternalTypeSymbol];
}
```

**Comment by moltar** [comment] 2019-11-03 17:48
You can see this use here, with all of the deps defined in package.json:

https://github.com/moltar/typescript-runtime-type-benchmarks/blob/427f1e18979e38b6c0497a303a564ad379f3cc5b/cases/ts-json-validator.ts#L27

**Comment by moltar** [comment] 2019-11-03 17:49
The IDE I'm using is VS Code (latest)

**Comment by ostrowr** [comment] 2019-11-03 18:04
Just cloned your repo and was able to replicate.

Looks like you're using Typescript 3.6.4 (which is a totally reasonable thing to be doing.)

However, `ts-json-validator` currently requires 3.7+ in order to work properly. (As I warn in the [README](https://github.com/ostrowr/ts-json-validator#%EF%B8%8F-warning-this-project-uses-some-features-from-typescript-37-which-is-not-yet-officially-released)

When npm-installing your repo, I get

`npm WARN ts-json-validator@0.1.1 requires a peer of typescript@>= 3.7.0 but none is installed. You must install peer dependencies yourself.`

Which I think is enough warning – but if you have an idea to make this more obvious, I'd welcome a suggestion/PR!

I've confirmed that this works in the IDE using 3.7 in your repo.

Closing this but feel free to reopen if you think I've missed something.

**Closed by ostrowr** 2019-11-03 18:04 UTC

**Comment by moltar** [comment] 2019-11-09 01:49
Ok, thanks for looking into this. What features of TS 3.7 is it relying on that are not available in 3.6.4? Thanks.

**Comment by moltar** [comment] 2019-11-09 02:20
Interestingly, after the update, the tests are failing.

```ts
export function caseTsJsonValidator(data: Data) {
  return parser.validate(data)
}
```

It seems return type of the function cannot be inferred and is set to `void` for some odd reason.

Even though when hovering the return type of `validate` in IDE, it shows it as a correct return type.

Any ideas?

**Comment by ostrowr** [comment] 2019-11-09 19:04
That's due to https://github.com/microsoft/TypeScript/issues/34596

I'm going to change this to a normal type guard for now (so .validate will return `true` if it validates, and will narrow the type, and `false` if not.)
