### ISSUE TITLE
Support additionalProperties: false

### ISSUE THREAD

**Issue by rubas** [ostrowr/ts-json-validator#21] opened 2019-12-07 10:50 UTC
It looks like `additionalProperties: false` is not supported.

**Type 'false' is not assignable to type 'SchemaLike | undefined'**

**Comment by ostrowr** [comment] 2019-12-08 04:40
Thanks! Yeah, I just haven't gotten around to implement this yet, but will ASAP. PRs also welcome :) 

I'm going to close this as a duplicate of #5 but feel free to comment on that with any more context.

**Closed by ostrowr** 2019-12-08 04:40 UTC

**Comment by ostrowr** [comment] 2019-12-20 07:10
This should be solved with the PR I just merged; I'll cut another release shortly.
